name: Plan and Apply Terraform

on:
  workflow_dispatch:
#  push:
#    branches:
#      - main

jobs:
  start-terraform:
    name: Start Terraform
    runs-on: ubuntu-latest

    steps:
      - name: Comment on PR that Terraform apply is running
        uses: mshick/add-pr-comment@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo-token-user-login: 'github-actions[bot]'
          message: |
            ***Running terraform apply***
            Results will display here momentarily...
            
          

