name : Deploy Lambda

on:
  workflow_dispatch:
permissions:
  id-token: write
  contents: read

jobs:
  deploy-lambda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.ROLE_ARN }}
          role-session-name: ${{ secrets.SESSION_NAME }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Zip
        run: |
            zip -j -r ./deploy.zip ./examples/lambda/*
      - name: Deploy to AuditStream Lambda
        run: |
            aws lambda update-function-code --function-name=cue-lambda --zip-file=fileb://deploy.zip
          
