name: Deploy to ECS

on:
  push:
    branches:
      - main
      -
jobs:
  publish-to-ecr:
    uses: shashimal/common-github-workflows/.github/workflows/deploy-ecr.yaml@main
    env:
      AWS_REGION: "us-east-1"
      ECR_REPOSITORY: "webapp"
    with:
      aws_region: ${{ env.AWS_REGION }}
      ecr_repository: ${{ env.ECR_REPOSITORY }}
      context: "./examples/ecr"
      file: "./examples/ecr/Dockerfile"
      tag_mutability: false
    secrets:
      iam_role_arn: ${{ secrets.AWS_GITHUB_IDENTITY_ROLE }}

  deploy-to-ecs:
    needs: [ publish-to-ecr ]
    uses: shashimal/common-github-workflows/.github/workflows/deploy-ecs.yaml@main
    env:
      AWS_REGION: "us-east-1"
      ECR_REPOSITORY: "webapp"
    with:
      aws_region: ${{ env.AWS_REGION }}
      cluster: 'test'
      service: "nginx-webapp-service"
      task_definition: "nginx-webapp"
      container_name: "nginx-webapp"
      image: ${secrets.AWS_ACCOUNT}.dkr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:${{ needs.publish-to-ecr.outputs.image-tag }}
    secrets:
      iam_role_arn: ${{ secrets.AWS_GITHUB_IDENTITY_ROLE }}
