name: Deploy to ECS

on:
  push:
    branches:
      - main
jobs:
  prepare-data:
    name: Preparing the required data
    runs-on: ubuntu-latest
    env:
      REGION: "us-east-1"
      REPOSITORY: "webapp"
    outputs:
      region: ${{ steps.region.outputs.region }}
      ecr_repo: ${{ steps.ecr_repo.outputs.ecr_repo }}

    steps:
      - name: Region
        id: region
        run: |
          echo "region=${{ env.REGION }}" >>$GITHUB_OUTPUT
        shell: bash

      - name: ECR Repo
        id: ecr_repo
        run: |
          echo "ecr_repo=${{ env.REPOSITORY }}" >>$GITHUB_OUTPUT
        shell: bash

  publish-to-ecr:
    needs: [ prepare-data ]
    uses: shashimal/common-github-workflows/.github/workflows/deploy-ecr.yaml@main
    with:
      aws_region: ${{ needs.prepare-data.outputs.region }}
      ecr_repository: ${{ needs.prepare-data.outputs.ecr_repo }}
      context: "./examples/ecr"
      file: "./examples/ecr/Dockerfile"
      tag_mutability: false
    secrets:
      iam_role_arn: ${{ secrets.AWS_GITHUB_IDENTITY_ROLE }}

  deploy-to-ecs:
    needs: [ publish-to-ecr , prepare-data ]
    uses: shashimal/common-github-workflows/.github/workflows/deploy-ecs.yaml@main
    with:
      aws_region: ${{ needs.prepare-data.outputs.region }}
      cluster: 'test'
      service: "nginx-webapp-service"
      task_definition: "nginx-webapp"
      container_name: "nginx-webapp"
      image: 793209430381.dkr.ecr.${{ needs.prepare-data.outputs.region }}.amazonaws.com/${{ needs.prepare-data.outputs.ecr_repo }}:${{ needs.publish-to-ecr.outputs.image-tag }}
    secrets:
      iam_role_arn: ${{ secrets.AWS_GITHUB_IDENTITY_ROLE }}
