name: Deploy to ECR

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  publish-to-ecr:
    uses: shashimal/common-github-workflows/.github/workflows/deploy-ecr.yaml@main
    with:
      aws_region: "us-east-1"
      ecr_repository: "webapp"
      context: "./ecr-example"
    secrets:
      iam_role_arn: ${{ secrets.AWS_GITHUB_IDENTITY_ROLE }}
