name: Plan and Apply Terraform

on:
  pull_request:
    branches:
      - main

#  workflow_dispatch:
#  push:
#    branches:
#      - main

jobs:
  start-terraform-plan:
    name: Starting Terraform plan
    runs-on: ubuntu-latest

    steps:
      - name: Comment on PR that Terraform plan is running
        uses: mshick/add-pr-comment@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo-token-user-login: 'github-actions[bot]'
          message: |
            ***Running terraform plan***
            Results will display here momentarily...

  terraform-plan:
    name: Running Terraform plan
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    strategy:
      fail-fast: false
      matrix:
        path:
          - dev
          - stg

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.ROLE_ARN }}
          role-session-name: ${{ secrets.SESSION_NAME }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.4

      - name: Terraform init
        run: |
          cd envs/${{ matrix.path }}
          terraform init -input=false





