name: Plan and Apply Terraform

on:
  pull_request:
    branches:
      - main

#  workflow_dispatch:
#  push:
#    branches:
#      - main

jobs:
  start-terraform-plan:
    name: Starting Terraform plan
    runs-on: ubuntu-latest

    steps:
      - name: Comment on PR that Terraform plan is running
        uses: mshick/add-pr-comment@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo-token-user-login: 'github-actions[bot]'
          message: |
            ***Running terraform plan***
            Results will display here momentarily...

  terraform-plan:
    name: Running Terraform plan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.4




